### ISSUE TITLE
Step 6 crashing on GBS data

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#150]
Running on Glenn's data step 6 crashes. I'm trying to debug it, but haven't spent a lot of time inside cluster_across, so i'm not super familiar with the internals. Here's the backtrace and the tail of the log file.
```
  Step6: Clustering across 94 samples at 0.85 similarity
  [####################] 100%  concat/shuf input     | 0:04:02 
  [####################] 100%  clustering across     | 0:58:27 
  [####################] 100%  aligning clusters     | 0:23:05 
  [####################] 100%  ordering clusters     | 0:11:40 
  [                    ]   0%  building database     | 0:00:00 ERROR:ipyrad.core.assembly:
  Caught unknown exception - 
  Saving Assembly.

Traceback (most recent call last):
  File "/home/iovercast/opt/miniconda/bin/ipyrad", line 9, in <module>
    load_entry_point('ipyrad==0.2.3', 'console_scripts', 'ipyrad')()
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad-0.2.3-py2.7.egg/ipyrad/__main__.py", line 361, in main
    data.run(steps=steps, force=args.force, preview=args.preview)
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad-0.2.3-py2.7.egg/ipyrad/core/assembly.py", line 1370, in run
    self.step6(force=force)            
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad-0.2.3-py2.7.egg/ipyrad/core/assembly.py", line 1325, in step6
    randomseed], 45)
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad-0.2.3-py2.7.egg/ipyrad/core/assembly.py", line 825, in _clientwrapper
    stepfunc(*args)
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad-0.2.3-py2.7.egg/ipyrad/core/assembly.py", line 1116, in _step6func
    force, randomseed, ipyclient)
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad-0.2.3-py2.7.egg/ipyrad/assemble/cluster_across.py", line 992, in run
    build_h5_array(data, samples, ipyclient)
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad-0.2.3-py2.7.egg/ipyrad/assemble/cluster_across.py", line 412, in build_h5_array
    multicat(data, samples, ipyclient)
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad-0.2.3-py2.7.egg/ipyrad/assemble/cluster_across.py", line 483, in multicat
    if jobs[sname].successful():
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 237, in successful
    assert self.ready()
AssertionError
```
```
2016-04-26 20:18:31,787     pid=7555    [cluster_across.py] INFO    building full database
2016-04-26 20:18:31,793     pid=7555    [cluster_across.py] INFO    submitting singlecat jobs
2016-04-26 20:22:04,586     pid=7597    [cluster_across.py] INFO    loading indels for cra-ant-72802-Huanuco-CarpaChavin_2 0, 35
2016-04-26 20:22:23,210     pid=7603    [cluster_across.py] INFO    loading indels for cra-ant-72822-LaLibertad-Suyubamba_2 1, 98
2016-04-26 20:22:43,584     pid=7590    [cluster_across.py] INFO    loading indels for cra-ant-72829-LaLibertad-ElMolino_2 2, 41
2016-04-26 20:22:52,013     pid=7600    [cluster_across.py] INFO    loading indels for cra-ant-72872-Piura-Landirca_2 3, 75
2016-04-26 20:23:57,242     pid=7555    [cluster_across.py] INFO    insert & cleanup : cra-ant-72822-LaLibertad-Suyubamba_2 sidx: 1
2016-04-26 20:24:50,431     pid=7555    [cluster_across.py] INFO    insert & cleanup : cra-ant-72802-Huanuco-CarpaChavin_2 sidx: 0
2016-04-26 20:25:58,780     pid=7555    [cluster_across.py] INFO    insert & cleanup : cra-ant-72872-Piura-Landirca_2 sidx: 3
2016-04-26 20:27:05,180     pid=7555    [cluster_across.py] INFO    insert & cleanup : cra-ant-72829-LaLibertad-ElMolino_2 sidx: 2
2016-04-26 20:28:14,448     pid=7555    [cluster_across.py] INFO    done filling superseqs
2016-04-26 20:28:14,457     pid=7555    [parallel.py]   INFO    Shutting down [ipyrad-7555] remote Engines
```

**Comment by Cycadales** [comment]
Hi I also get this same issue or similar in step 7.
Caught unknown exception - TypeError(ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'')
Saving Assembly.
Traceback (most recent call last):
File "/Users/James/miniconda2/bin/ipyrad", line 9, in <module>
load_entry_point('ipyrad==0.2.5', 'console_scripts', 'ipyrad')()
File "/Users/James/miniconda2/lib/python2.7/site-packages/ipyrad/main.py", line 361, in main
data.run(steps=steps, force=args.force, preview=args.preview)
File "/Users/James/miniconda2/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 1372, in run
self.step7(force=force)
File "/Users/James/miniconda2/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 1341, in step7
self._clientwrapper(self._step7func, [samples, force], 45)
File "/Users/James/miniconda2/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 825, in _clientwrapper
stepfunc(*args)
File "/Users/James/miniconda2/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 1159, in _step7func
assemble.write_outfiles.run(self, samples, force, ipyclient)
File "/Users/James/miniconda2/lib/python2.7/site-packages/ipyrad/assemble/write_outfiles.py", line 68, in run
filter_all_clusters(data, samples, ipyclient)
File "/Users/James/miniconda2/lib/python2.7/site-packages/ipyrad/assemble/write_outfiles.py", line 303, in filter_all_clusters
[i.get() for i in results]
File "/Users/James/miniconda2/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 160, in get
raise self.exception()
ipyparallel.error.RemoteError: TypeError(ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'')

**Comment by dereneaton** [comment]
I believe this is now fixed. Let me know if it works for you in v.0.2.8.

**Comment by Cycadales** [comment]
Thank you! I will run it now and check.

Ph.D. Student
Royal Botanic Garden Sydney and
Royal Botanic Garden Edinburgh

Blog:http://cycadconservation.blogspot.com.au<http://cycadconservation.blogspot.com.au/>
Video portfolio: https://vimeo.com/user36654226

Sent from my iPhone

On 16 May 2016, at 15:46, Deren Eaton <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe this is now fixed. Let me know if it works for you in v.0.2.8.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/dereneaton/ipyrad/issues/150#issuecomment-219353402>

--
The Royal Botanic Garden Edinburgh is a charity registered in Scotland (No SC007983)

**Comment by Cycadales** [comment]
Daren, are you putting this update out for the mac too?


On 16 May 2016, at 3:46 PM, Deren Eaton <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe this is now fixed. Let me know if it works for you in v.0.2.8.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/dereneaton/ipyrad/issues/150#issuecomment-219353402>


--
The Royal Botanic Garden Edinburgh is a charity registered in Scotland (No SC007983)

**Comment by isaacovercast** [comment]
fixed
