### ISSUE TITLE
Problem w/ CLI merging

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#155]
I tried to merge glenn's 3 plates of gbs data and i'm getting:
```
Traceback (most recent call last):                                                                                                                   
  File "/home/iovercast/opt/miniconda/bin/ipyrad", line 9, in <module>                                                                               
    load_entry_point('ipyrad==0.3.7', 'console_scripts', 'ipyrad')()                                                                                 
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad/__main__.py", line 452, in main                                             
    data.run(steps=steps, force=args.force, preview=args.preview)                                                                                    
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 1385, in run                                        
    self.step2(force=force, preview=preview)                                                                                                         
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 1247, in step2                                      
    [samples, nreplace, force, preview], 45)                                                                                                         
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 847, in _clientwrapper                              
    stepfunc(*args)                                                                                                                                  
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 1010, in _step2func                                 
    assemble.rawedit.run(self, samples, nreplace, force, preview, ipyclient)                                                                         
  File "/home/iovercast/opt/miniconda/lib/python2.7/site-packages/ipyrad/assemble/rawedit.py", line 745, in run                                      
    if os.path.exists(sample.files.fastqs[0][1]):                                                                                                    
IndexError: tuple index out of range
```

Still investigating...

**Comment by isaacovercast** [comment]
fixed
