### ISSUE TITLE
User Error - CRC check fails

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#170]
I thought we'd seen this before but i forget what the problem was. Yaoxin reports this:

```
===================the error message===============================
[yaoxin@smp01 sy_20160716]$ ipyrad -f -p params-youdan.txt -s 1 -c 45      

 --------------------------------------------------
  ipyrad [v.0.3.20]
  Interactive assembly and analysis of RADseq data
 --------------------------------------------------
  New Assembly: youdan
  ipyparallel setup: Local connection to 45 Engines

  Step1: Linking sorted fastq data to Samples
    Linking to demultiplexed fastq files in:
      /lustre/home/yaoxin/data/rad/sy_20160716/data01/*.fq.gz
ERROR:ipyrad.core.assembly:IOError: CRC check failed 0x7c9e787c != 0x2c514cdbL

Traceback (most recent call last):
  File "/lustre/home/yaoxin/miniconda2/bin/ipyrad", line 9, in <module>
    load_entry_point('ipyrad==0.3.20', 'console_scripts', 'ipyrad')()
  File "/lustre/home/yaoxin/miniconda2/lib/python2.7/site-packages/ipyrad/__main__.py", line 456, in main
    data.run(steps=steps, force=args.force, preview=args.preview)
  File "/lustre/home/yaoxin/miniconda2/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 1410, in run
    self.step1(force=force, preview=preview)
  File "/lustre/home/yaoxin/miniconda2/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 1228, in step1
    self._clientwrapper(self._step1func, [force, preview], 45)
  File "/lustre/home/yaoxin/miniconda2/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 864, in _clientwrapper
    stepfunc(*args)
  File "/lustre/home/yaoxin/miniconda2/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 994, in _step1func
    self.link_fastqs()
  File "/lustre/home/yaoxin/miniconda2/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 449, in link_fastqs
    nreads += bufcountlines(alltuples[0], gzipped)
  File "/lustre/home/yaoxin/miniconda2/lib/python2.7/site-packages/ipyrad/core/assembly.py", line 1589, in bufcountlines
    buf = read_f(buf_size)
  File "/lustre/home/yaoxin/miniconda2/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/lustre/home/yaoxin/miniconda2/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/lustre/home/yaoxin/miniconda2/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x7c9e787c != 0x2c514cdbL
```
I'm having them update to newest version, but i don't think that'll fix it....

**Comment by dereneaton** [comment]
It looks like the error is arising when trying to read in the the fastq files with `link_fastqs()`. Did Yaoxin use ipyrad to do the demultiplexing? If so, one guess that I have is that the files are perhaps becoming corrupted we do demultiplexing on machines with many cores because there are too many processes tying to do I/O at the same time and the system freaks out. I raised a separate issue about trying to change several steps to only have a "single writer engine" framework, which I might fix this. I Yaoxin did not do demultiplexing in ipyrad then I'm not sure what the problem would be...

**Comment by isaacovercast** [comment]
Fixed their own problem, some kind of issue with the demultiplexed reads being imported. From the user: "The reason making the error is that i didn't give the full direction of folder containing demultiplexed data. It should be like ./data01/*.gz, but I just imput data01."

I can't reproduce this, even though i tried....
