### ISSUE TITLE
cutadapt is failing strangely, something todo with eggs

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#197]
Got the following error when running the API on a cluster. It still took a long time to run, but then just pooped out an error about not being able to run cutadapt. Quite strange. This is on v.0.4.6.

```  
Assembly: c85d5f2h5
  [####################] 100%  loading reads         | 0:01:38 | s1 | 
  [####################] 100%  processing reads      | 1:44:39 | s2 | 

  Encountered an unexpected error (see ./ipyrad_log.txt)
  Error message is below -------------------------------
IPyradError((' error in %s, %s', ['cutadapt', '-A', 'CTGCAAAGCAAGAGATCGGAAGAGC', '-a', 'CTGCAAGATCGGAAGAGC', '--quality-cutoff', '20,20', '-u', '0', '-U', '0', '--trim-n', '--quality-base', '33', '--max-n', '5', '--minimum-length', '35', '-o', '/ysm-gpfs/scratch60/de243/WB-PED/c85d5f2h5/c85d5f2h5_edits/d39114.trimmed_R1_.fastq.gz', '-p', '/ysm-gpfs/scratch60/de243/WB-PED/c85d5f2h5/c85d5f2h5_edits/d39114.trimmed_R2_.fastq.gz', '/ysm-gpfs/scratch60/de243/WB-PED/demux_reads/WB-PED_demux_fastqs/d39114_R1_.fastq.gz', '/ysm-gpfs/scratch60/de243/WB-PED/demux_reads/WB-PED_demux_fastqs/d39114_R2_.fastq.gz'], 'Traceback (most recent call last):\n  File "/ysm-gpfs/home/de243/miniconda2/bin/cutadapt", line 4, in <module>\n    __import__(\'pkg_resources\').run_script(\'cutadapt==1.11\', \'cutadapt\')\n  File "/ysm-gpfs/home/de243/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 726, in run_script\n  File "/ysm-gpfs/home/de243/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1491, in run_script\n  File "/ysm-gpfs/home/de243/miniconda2/lib/python2.7/site-packages/cutadapt-1.11-py2.7-linux-x86_64.egg/EGG-INFO/scripts/cutadapt", line 9, in <module>\n    \n  File "build/bdist.linux-x86_64/egg/cutadapt/scripts/cutadapt.py", line 62, in <module>\n  File "build/bdist.linux-x86_64/egg/cutadapt/__init__.py", line 11, in check_importability\n  File "build/bdist.linux-x86_64/egg/cutadapt/_align.py", line 7, in <module>\n  File "build/bdist.linux-x86_64/egg/cutadapt/_align.py", line 4, in __bootstrap__\n  File "/ysm-gpfs/home/de243/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1152, in resource_filename\n  File "/ysm-gpfs/home/de243/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1696, in get_resource_filename\n  File "/ysm-gpfs/home/de243/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1726, in _extract_resource\n  File "/ysm-gpfs/home/de243/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1219, in get_cache_path\n  File "/ysm-gpfs/home/de243/miniconda2/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/__init__.py", line 1199, in extraction_error\npkg_resources.ExtractionError: Can\'t extract file(s) to egg cache\n\nThe following error occurred while trying to extract file(s) to the Python egg\ncache:\n\n  [Errno 17] File exists: \'/ysm-gpfs/home/de243/.python-eggs\'\n\nThe Python egg cache directory is currently set to:\n\n  /ysm-gpfs/home/de243/.python-eggs\n\nPerhaps your account does not have write access to this directory?  You can\nchange the cache directory by setting the PYTHON_EGG_CACHE environment\nvariable to point to an accessible directory.\n\n'))
```

**Comment by dereneaton** [comment]
Strangely, it is complaining about some kind of import error, but all of the other 47 samples finished just fine, only the one sample failed.

**Comment by dereneaton** [comment]
As one small fix I made a change so that step2 will not bonk out if one sample fails, but will still save the state=2 and stats for the other samples.

**Comment by dereneaton** [comment]
I haven't seen this again. Maybe it was a one time thing? Seems fixed.
