### ISSUE TITLE
Problem install ipyrad

### ISSUE THREAD

**Issue by tangerzhang** [dereneaton/ipyrad#231]
Hi,
I am trying to install ipyrad however I got error like this:
Is there any way to solve this? Thanks!
Traceback (most recent call last):
  File "/public1/home/coop_wg/miniconda2/bin/ipyrad", line 11, in <module>
    load_entry_point('ipyrad==0.5.9', 'console_scripts', 'ipyrad')()
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
    
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
    
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
    
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
    
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/ipyrad-0.5.9-py2.7.egg/ipyrad/__init__.py", line 22, in <module>
    from . import load
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/ipyrad-0.5.9-py2.7.egg/ipyrad/load/__init__.py", line 13, in <module>
    from .load import test_assembly
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/ipyrad-0.5.9-py2.7.egg/ipyrad/load/load.py", line 14, in <module>
    from ipyrad.assemble.util import *
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/ipyrad-0.5.9-py2.7.egg/ipyrad/assemble/__init__.py", line 8, in <module>
    from . import cluster_across
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/ipyrad-0.5.9-py2.7.egg/ipyrad/assemble/cluster_across.py", line 21, in <module>
    import numba
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/numba-0.31.0-py2.7-linux-x86_64.egg/numba/__init__.py", line 9, in <module>
    from . import config, errors, runtests, types
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/numba-0.31.0-py2.7-linux-x86_64.egg/numba/config.py", line 11, in <module>
    import llvmlite.binding as ll
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/llvmlite-0.16.0-py2.7.egg/llvmlite/binding/__init__.py", line 6, in <module>
    from .dylib import *
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/llvmlite-0.16.0-py2.7.egg/llvmlite/binding/dylib.py", line 4, in <module>
    from . import ffi
  File "/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/llvmlite-0.16.0-py2.7.egg/llvmlite/binding/ffi.py", line 50, in <module>
    raise e
OSError: /public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/llvmlite-0.16.0-py2.7.egg/llvmlite/binding/libllvmlite.so: cannot open shared object file: No such file or directory

**Comment by isaacovercast** [comment]
Hello,
Please try upgrading to the newest version of ipyrad and see if that fixes
the problem:

conda install -c ipyrad ipyrad

let me know how it goes.
-isaac

**Comment by tangerzhang** [comment]
Thanks for you response.
I switched ipyrad to the newest version (0.6.6) but still got the same
error:

Traceback (most recent call last):
  File "/public1/home/coop_wg/miniconda2/bin/ipyrad", line 11, in <module>
    load_entry_point('ipyrad==0.6.6', 'console_scripts', 'ipyrad')()
  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py",
line 565, in load_entry_point

  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py",
line 2598, in load_entry_point

  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py",
line 2258, in load

  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py",
line 2264, in resolve

  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/ipyrad-0.6.6-py2.7.egg/ipyrad/__init__.py",
line 20, in <module>
    from . import load as _load
  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/ipyrad-0.6.6-py2.7.egg/ipyrad/load/__init__.py",
line 13, in <module>
    from .load import test_assembly
  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/ipyrad-0.6.6-py2.7.egg/ipyrad/load/load.py",
line 14, in <module>
    from ipyrad.assemble.util import *
  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/ipyrad-0.6.6-py2.7.egg/ipyrad/assemble/__init__.py",
line 5, in <module>
    from . import jointestimate
  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/ipyrad-0.6.6-py2.7.egg/ipyrad/assemble/jointestimate.py",
line 10, in <module>
    import numba
  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/numba-0.31.0-py2.7-linux-x86_64.egg/numba/__init__.py",
line 9, in <module>
    from . import config, errors, runtests, types
  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/numba-0.31.0-py2.7-linux-x86_64.egg/numba/config.py",
line 11, in <module>
    import llvmlite.binding as ll
  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/llvmlite-0.16.0-py2.7.egg/llvmlite/binding/__init__.py",
line 6, in <module>
    from .dylib import *
  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/llvmlite-0.16.0-py2.7.egg/llvmlite/binding/dylib.py",
line 4, in <module>
    from . import ffi
  File
"/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/llvmlite-0.16.0-py2.7.egg/llvmlite/binding/ffi.py",
line 50, in <module>
    raise e
OSError:
/public1/home/coop_wg/miniconda2/lib/python2.7/site-packages/llvmlite-0.16.0-py2.7.egg/llvmlite/binding/libllvmlite.so:
cannot open shared object file: No such file or directory

2017-03-01 2:24 GMT+08:00 Isaac Overcast <notifications@github.com>:

**Comment by isaacovercast** [comment]
This could be a python path issue in which case you should try this:

http://ipyrad.readthedocs.io/faq.html?highlight=PYTHONPATH#other-random-problems-with-solutions

It also could be that your install of miniconda is wonky, so you could try deleting your miniconda directory and reinstalling. This is probably the most reliable way to fix conda problems.

**Comment by isaacovercast** [comment]
Or try running ipyrad inside a conda env:

conda env create --name test_ipyrad
