### ISSUE TITLE
interrupted step 6

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#243]
I tried adding an additional checkpoint into step 6 so that if a job was interrupted before finished indexing + databaseing, it would not need to also redo the clustering. It seems to be failing though (in 0.6.19). User comment on gitter:
 
```
@isaacovercast @dereneaton Hello, I've hit another problem with my run. It was on step 6 and seemed almost done before stopping again due to walltime limits:
Step 6: Clustering at 0.9 similarity across 288 samples
[####################] 100% concat/shuffle input | 0:02:15
[####################] 100% clustering across | 3 days, 16:55:37
[####################] 100% building clusters | 0:04:02
[####################] 100% aligning clusters | 1:44:17
[####################] 100% database indels | 0:21:33
[####################] 100% indexing clusters | 3:28:41
[###### ] 31% building database | 2 days, 11:05:59 =>> PBS: job killed: walltime 604836 exceeded limit 604800
```
When I started it again, I ran it for only 24 hrs (usually I can run for a week at a time), because they were going to do maintenance on the cluster. That run gave a lot of errors in the log and also seemed to have switched where it was within step 6 (claiming it was at 33% building clusters instead of building database):
```
Step 6: Clustering at 0.9 similarity across 288 samples
[###### ] 33% building clusters | 0:41:14 ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
File "/home/jkarch/miniconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
callback(args, **kwargs)
File "/home/jkarch/miniconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
return fn(args, kwargs)
File "<decorator-gen-140>", line 2, in _dispatch_reply
File "/home/jkarch/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py", line 71, in unpack_message
return f(self, msg)
File "/home/jkarch/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py", line 885, in _dispatch_reply
raise KeyError("Unhandled reply message type: %s" % msg_type)
KeyError: u'Unhandled reply message type: apply_request'
ERROR:tornado.general:Uncaught exception, closing connection.
Traceback (most recent call last):
File "/home/jkarch/miniconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
self._handle_recv()
File "/home/jkarch/miniconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
self._run_callback(callback, msg)
File "/home/jkarch/miniconda2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
callback(*args, kwargs)
File "/home/jkarch/miniconda2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
return fn(args, *kwargs)
File "<decorator-gen-140>", line 2, in _dispatch_reply
File "/home/jkarch/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py", line 71, in unpack_message
return f(self, msg)
File "/home/jkarch/miniconda2/lib/python2.7/site-packages/ipyparallel/client/client.py", line 885, in _dispatch_reply
raise KeyError("Unhandled reply message type: %s" % msg_type)
[etc, portion deleted]
[###### ] 33% building clusters | 23:59:30 =>> PBS: job killed: walltime 86411 exceeded limit 86400
I did another 24 hr run once the cluster was back up, as a test, and it did not give errors, but it didn't seem to make any progress either (still said 33% building clusters) and our cluster help guy said it was using almost no CPU and only one node (despite me requesting 20).
Any suggestions?
```

**Comment by dereneaton** [comment]
You can now restart step 6 from a checkpoint if it is interrupted. The CLI will automatically detect where it left off. The API will as well, or you can designate the 'substep' that it should run, of which there are 7. API example below. 

Interrupted analysis
```
data.run("6", force=True)

Assembly: cli
[####################] 100%  concat/shuffle input  | 0:00:00 | s6 | 
[####################] 100%  clustering across     | 0:00:01 | s6 | 
[####################] 100%  building clusters     | 0:00:00 | s6 | 
[######              ]  33%  aligning clusters     | 0:00:02 | s6 | 
```

Restarted from substep 4 (aligning)
```
data.run("6", force=True, substeps=[4, 5, 6, 7])

Assembly: cli
Continuing from checkpoint 6.4
[####################] 100%  aligning clusters     | 0:00:00 | s6 | 
[####################] 100%  database indels       | 0:00:01 | s6 | 
[####################] 100%  indexing clusters     | 0:00:03 | s6 | 
[####################] 100%  building database     | 0:00:00 | s6 | 
```
