### ISSUE TITLE
error in step 6 IndexError(boolean index did not match

### ISSUE THREAD

**Issue by Wind-ant** [dereneaton/ipyrad#253]
**When I run step 6,after it finished,logfile show me like this:**
Encountered an error (see details in ./ipyrad_log.txt)
  Error summary is below -------------------------------
error in step 6 IndexError(boolean index did not match indexed array along dimension 0; dimension is 107 but corresponding boolean dimension is 106)
**So I open the  ipyrad_log.txt:**
2017-07-21 11:27:46,305         pid=128313      [cluster_across.py]     ERROR   error in persistent_popen_align IndexError(boolean index did not match indexed array along dimension 0; dimension is 107 but corresponding boolean dimension is 106)
2017-07-21 11:27:46,307         pid=128313      [assembly.py]   ERROR   IPyradWarningExit: error in step 6 IndexError(boolean index did not match indexed array along dimension 0; dimension is 107 but corresponding boolean dimension is 106)
Do anyone know what happens?

**Comment by aduffy70** [comment]
I am seeing this as well. Tried on ipyrad v0.6.27 and 0.7.1 (can't try 0.7.2 due to pysam issues on CentOS7): 
Platform info: ('Linux', 'kp379', '3.10.0-327.36.3.el7.x86_64', '#1 SMP Mon Oct 24 16:09:20 UTC 2016', 'x86_64')
2017-07-21 09:56:51,944       pid=142117      [cluster_across.py]     ERROR   error in persistent_popen_align IndexError(boolean index did not match indexed array along dimension 0; dimension is 93 but corresponding boolean dimension is 92)
2017-07-21 09:56:55,347         pid=142117      [assembly.py]   ERROR   IPyradWarningExit: error in step 6 IndexError(boolean index did not match indexed array along dimension 0; dimension is 93 but corresponding boolean dimension is 92)

**Comment by aduffy70** [comment]
I downgraded numpy from 1.13.1 to 1.12.1 and step 6 finished successfully.

**Comment by Wind-ant** [comment]
Could you tell me how to downgrade numpy?I don't know how to do.
Thx~

**Comment by Wind-ant** [comment]
I couldn't find numpy in the miniconda filefold,neither can I downgrade it~

**Comment by aduffy70** [comment]
conda install numpy=1.12.1

**Comment by Wind-ant** [comment]
Thanks a lot,it worked!

**Comment by Wind-ant** [comment]
another question,why quality of all the loci in the vcf file is the same,like 13?and the coverage is too low,loci in many samples are missing.Should i change some parameters to be more optimal？
THX

**Comment by isaacovercast** [comment]
A better place for this question would be the ipyrad gitter channel:
https://gitter.im/dereneaton/ipyrad

**Comment by isaacovercast** [comment]
If you set the min samples per locus setting it'll decrease the amount of missing data, at the expense of throwing away some information. Hope over to the gitter channel if you have more specific questions.

**Comment by isaacovercast** [comment]
Confirm I can recreate this error (on the dolphin ddrad dataset from the manuscript analysis):
```
   pid=17804       [cluster_across.py]     ERROR   error in persistent_popen_align IndexError(boolean index did not match indexed array along dimension 0; dimension is 199 but corresponding boolean dimension is 198)                                                                                   
2017-07-23 15:38:50,753         pid=17804       [assembly.py]   ERROR   IPyradWarningExit: error in step 6 IndexError(boolean index did not match indexed array along dimension 0; dimension is 199 but corresponding boolean dimension is 198)  
```

**Comment by isaacovercast** [comment]
Behavior of masked arrays changed in numpy 1.12 -> 1.13:
```
>>> mask = np.ones(10, np.bool_)
>>> short = np.arange(9)
>>> long = np.arange(11)
>>> short[mask == 1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index 9 is out of bounds for axis 1 with size 9
>>> long[mask == 1]
__main__:1: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 11 but corresponding boolean dimension is 10
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> quit()

isaac@goatzilla:~/isaac$ conda install numpy -f

>>> mask = np.ones(10, np.bool_)
>>> short = np.arange(9)
>>> long = np.arange(11)
>>> short[mask == 1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: boolean index did not match indexed array along dimension 0; dimension is 9 but corresponding boolean dimension is 10
>>> long[mask == 1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: boolean index did not match indexed array along dimension 0; dimension is 11 but corresponding boolean dimension is 10
```

**Comment by isaacovercast** [comment]
Ugh, this is so annoying:
```
                        if any(indidx):
                            allrows = np.arange(amask.shape[1])
                            mask = np.ones(allrows.shape[0], dtype=np.bool_)
                            for idx in indidx:
                                if idx < mask.shape[0]:
                                    mask[idx] = False
                            not_idx = allrows[mask == 1]
                            ## fill in new data into all other spots
                            newmask[not_idx] = amask[kidx, :not_idx.shape[0]]
                        else:
                            newmask = amask[kidx]
```
any returns false for an empty array, but also for an array with one element so long as that one element is zero. Wat?! Changed the call to `any()` to `indidx.size`.
