### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'jupyter' distribution was not found

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#279]
I can reproduce this on linux by removing the miniconda directory and then doing a clean install.

```
dorseylabmacbook:~ bdorsey$ ipyrad -v
Traceback (most recent call last):
  File "/Users/bdorsey/miniconda2/bin/ipyrad", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/bdorsey/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/Users/bdorsey/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3122, in _call_aside
    f(*args, **kwargs)
  File "/Users/bdorsey/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/bdorsey/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 664, in _build_master
    ws.require(__requires__)
  File "/Users/bdorsey/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/bdorsey/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jupyter' distribution was not found and is required by ipyrad
```

**Comment by isaacovercast** [comment]
```
isaac@isaacovercast:~/ipyrad$ pip list | grep jupyter                                                                                                                   
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under 
the [list] section) to disable this warning.                                                                                                                            
jupyter-client (5.1.0)                                                                                                                                                  
jupyter-console (5.2.0)
jupyter-core (4.3.0)  
```

jupyter not getting installed according to pip.

**Comment by isaacovercast** [comment]
If you do a straight `python setup.py install` it pulls down jupyter, but the conda build doesn't do it right.

**Comment by isaacovercast** [comment]
I think this is a collision with other local python install. This was informative but not exactly useful: https://github.com/conda/conda/issues/508

**Comment by isaacovercast** [comment]
Also informative. Also, the conda build breaks on systems that display this behavior.

**Comment by cb1579** [comment]
> If you do a straight python setup.py install it pulls down jupyter, but the conda build doesn't do it right.

Could you elaborate? I'm having this issue after using miniconda to install ipyrad.

Thanks.

**Comment by isaacovercast** [comment]
I don't exactly understand yet myself. The conda build process uses setup.py internally, but something about the conda build environment isn't pulling in requirements right. You can fix this for now by doing `pip install jupyter`.

**Comment by cb1579** [comment]
Wow, thanks for the rapid response. This appears to have solved my issue, as ipyrad is now running. 

Thanks!

**Comment by eaton-lab** [comment]
This is now fixed in v.0.7.18
