### ISSUE TITLE
TypeError Can't broadcast 

### ISSUE THREAD

**Issue by jeffinrockey** [dereneaton/ipyrad#305]
Dear Deren,
Please see the error below.
version: ipyrad 0.7.28
Could you please let me know what would be causing this.

[####################] 100%  chunking clusters     | 0:00:33 | s5 |
[####################] 100%  consens calling       | 0:28:39 | s5 |
[####################] 100%  concat/shuffle input  | 0:01:32 | s6 |
[####################] 100%  clustering across     | 3:19:17 | s6 |
[####################] 100%  building clusters     | 0:01:20 | s6 |
[####################] 100%  aligning clusters     | 0:08:43 | s6 |
[################### ]  99%  database indels       | 0:04:49 | s6 |
  Encountered an unexpected error (see ./ipyrad_log.txt)
  Error message is below -------------------------------
TypeError(Can't broadcast (100, 1130, 133) -> (100, 187, 133))

**Comment by isaacovercast** [comment]
Can you re-run step 6 with the -d flag and paste the last 2 or 3 dozen
lines of the ipyrad_log.txt file? It'll help with debugging.

**Comment by isaacovercast** [comment]
Did you do any branching and subsampling during this assembly?

**Comment by isaacovercast** [comment]
Now it's my turn to apologize for the delay, I was at Evolution in France.

Looks like you are using API mode (which is cool!), the easiest way to use the debug flag is through the CLI, so you could do something like this in a new notebook cell:

```
data1.write_params("params-tmp.txt")
!ipyrad -p params-tmp.txt -s 6 -f -d
```

This will write the params to a file, then it will run only step 6 with the debug turned on.

**Comment by jeffinrockey** [comment]
Hi Isaac,
   I executed the two lines as advised. First line in python and second line in CLI subsequently. Still error occurring but this time error log is more informative . Please see below and let me know what can be done to rectify.
Jeffin  

Step 6: Clustering at 0.85 similarity across 100 samples
  [####################] 100%  concat/shuffle input  | 0:01:33
  [####################] 100%  clustering across     | 3:18:39
  [####################] 100%  building clusters     | 0:01:19
  [####################] 100%  aligning clusters     | 0:09:33
  [################### ]  99%  database indels       | 0:04:27
  Encountered an unexpected error (see ./ipyrad_log.txt)
  Error message is below -------------------------------
TypeError(Can't broadcast (100, 1130, 133) -> (100, 187, 133))
Traceback (most recent call last):
  File "/home/jeffin.r/anaconda2/bin/ipyrad", line 11, in <module>
    load_entry_point('ipyrad==0.7.28', 'console_scripts', 'ipyrad')()
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/ipyrad/__init__.py", line 20, in <module>
    from . import load as _load
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/ipyrad/load/__init__.py", line 14, in <module>
    from .load import test_assembly
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/ipyrad/load/load.py", line 14, in <module>
    from ipyrad.assemble.util import IPyradWarningExit, ObjDict
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/ipyrad/assemble/__init__.py", line 5, in <module>
    from . import demultiplex
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/ipyrad/assemble/demultiplex.py", line 22, in <module>
    from ipyrad.core.sample import Sample
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/ipyrad/core/__init__.py", line 5, in <module>
    from . import parallel
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/ipyrad/core/parallel.py", line 8, in <module>
    import ipyparallel as ipp
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/ipyparallel/__init__.py", line 11, in <module>
    import zmq
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/jeffin.r/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /home/jeffin.r/anaconda2/lib/python2.7/site-packages/matplotlib/../../../libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/jeffin.r/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/../../../../../libzmq.so.5.1.2)

**Comment by isaacovercast** [comment]
Are you running on a cluster? The GLIBC error is normally a problem on older HPC systems with old, out of date GLIBC installs.

**Comment by jeffinrockey** [comment]
Dear Isaac ,
  I checked with our admin on the GLIBC issue.  It was due to an anaconda mix up. Deleted and re-installed conda and ipyrad. The GLIBC went away. However at step 6 the actual broad cast error resurfaced even with the -d -f option from CLI. 

I ran the program in Redhat as well as Ubuntu servers. The issue persists.

Is there anything else that I may try to get over this issue. 

Jeffin

**Comment by isaacovercast** [comment]
The `-d` option just turns on debug mode, it won't fix anything, and the `-f` option forces overwriting previous results. Can you paste here the last 20-30 lines of the ipyrad_log.txt file?

**Comment by jeffinrockey** [comment]
Hi Isaac,
   The below is the only entry in the file.Please see.
Jeffin

file reset2018-09-07 13:43:02,594       pid=16394       [assembly.py]   ERROR   TypeError(Can't broadc
ast (100, 1130, 133) -> (100, 187, 133))
ipyrad_log.txt (END)

Sent from my BlackBerry 10 smartphone.
From: Isaac Overcast
Sent: Tuesday 11 September 2018 6:39 PM
To: dereneaton/ipyrad
Reply To: dereneaton/ipyrad
Cc: Jeffin Rockey; Author
Subject: Re: [dereneaton/ipyrad] TypeError Can't broadcast (#305)



The -d option just turns on debug mode, it won't fix anything, and the -f option forces overwriting previous results. Can you paste here the last 20-30 lines of the ipyrad_log.txt file?

**Comment by isaacovercast** [comment]
The file got blanked. Can you run ipyrad step 6 with the -d flag again, there should be hundreds or thousands of lines of output in the ipyrad_log.txt file.

**Comment by jeffinrockey** [comment]
Hi Isaac,
  The last few lines of ipyrad_log.txt are as below. Please see and advise.
```
2018-09-12 07:38:11,893         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2360, 133)
2018-09-12 07:38:11,893         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:11,985         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2360, 133)
2018-09-12 07:38:11,986         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:12,145         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2360, 133)
2018-09-12 07:38:12,145         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:12,299         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2360, 133)
2018-09-12 07:38:12,300         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:12,527         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2360, 133)
2018-09-12 07:38:12,528         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:12,726         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2360, 133)
2018-09-12 07:38:12,726         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:12,912         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2360, 133)
2018-09-12 07:38:12,912         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:13,171         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2360, 133)
2018-09-12 07:38:13,171         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:13,415         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2360, 133)
2018-09-12 07:38:13,415         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:13,633         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2360, 133)
2018-09-12 07:38:13,633         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:13,884         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2360, 133)
2018-09-12 07:38:13,884         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:14,059         pid=17622       [cluster_across.py]     INFO    inarr shape (100, 2248, 133)
2018-09-12 07:38:14,059         pid=17622       [cluster_across.py]     INFO    iset shape (100, 513443, 133)
2018-09-12 07:38:22,096         pid=17570       [assembly.py]   ERROR   TypeError(Can't broadcast (100, 2248, 133) -> (100, 1323, 133))
2018-09-12 07:38:24,799         pid=17570       [assembly.py]   INFO      shutting down engines
2018-09-12 07:38:26,002         pid=17570       [assembly.py]   INFO      finished shutdown
2018-09-12 07:38:26,071         pid=17570       [__init__.py]   INFO    debugging turned off

```

**Comment by isaacovercast** [comment]
hm. Can you zip up the *_across directory and dropbox it to me? I can't figure it out without looking at the data. Or you can send the raw sample data..

**Comment by jeffinrockey** [comment]
Dear Isaac, 
   I cannot really share the raw data or any sample specific data. It is not the data size or so that is the problem, other restrictions instead. Very sorry about this limitation.  
Would you please share me a public/test data set link, which  I shall download and then run ipyrad for it in the server. This way we can gather the whole data required to resolve.
Let me know you thought on this alternative.

**Comment by jeffinrockey** [comment]
Dear Isaac,
    At last got it working. It was my mistake indeed. The restriction site overhang given was incorrect. It lead to 0 filtered for almost all samples ,thereby causing broadcast error downstream.

Very much appreciate your support in resolving. I am closing this issue.Thanks to you again, Isaac.

Jeffin
