### ISSUE TITLE
installed conda ,but conda update and conda install are available

### ISSUE THREAD

**Issue by marathonwxm** [dereneaton/ipyrad#309]
I've installed conda,but,it couldn't update or install ipyrad.
[图片]
[图片]
[图片]
,I also tried rm -rf ~/miniconda2 to uninstall and re install miniconda2,it didn't work.Could you help me check it?

**Comment by marathonwxm** [comment]
[wxm@localhost miniconda2]$ conda -V
conda 4.5.11
[wxm@localhost miniconda2]$ conda update conda
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 14, in execute
        install(args, parser, 'update')
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 235, in install
        force_reinstall=context.force,
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/core/solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/core/solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 183, in query_all
        futures = tuple(executor.submit(sd.query, spec) for sd in subdir_datas)
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 183, in <genexpr>
        futures = tuple(executor.submit(sd.query, spec) for sd in subdir_datas)
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/conda/common/io.py", line 451, in submit
        self._adjust_thread_count()
      File "/home/wxm/miniconda2/lib/python2.7/site-packages/concurrent/futures/thread.py", line 149, in _adjust_thread_count
        t.start()
      File "/home/wxm/miniconda2/lib/python2.7/threading.py", line 736, in start
        _start_new_thread(self.__bootstrap, ())
    error: can't start new thread

`$ /home/wxm/miniconda2/bin/conda update conda`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/home/wxm/miniconda2
                     PATH=/home/wxm/miniconda2/pkgs:/home/wxm/miniconda2/bin:/home/wxm/miniconda
                          2/bin:/home/wxm/miniconda2/pkgs:/home/wxm/miniconda2/bin:/usr/lib64/qt
                          -3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:
                          /home/wxm/bin:/home/wxm/miniconda2/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/wxm/.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : /home/wxm/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/wxm/miniconda2/pkgs
                          /home/wxm/.conda/pkgs
       envs directories : /home/wxm/miniconda2/envs
                          /home/wxm/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/2.7.15 Linux/2.6.32-642.el6.x86_64 rhel/6.8 glibc/2.17
                UID:GID : 506:506
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

[wxm@localhost miniconda2]$

**Comment by isaacovercast** [comment]
Did you try the conda gitter channel? This is not an ipyrad issue.

**Comment by marathonwxm** [comment]
Yeah, I have seen the gitter, the problem isn't solved.I'm sorry.
