### ISSUE TITLE
bb.generate_tests_from_tree ToyTree AttributeError (baba.py)

### ISSUE THREAD

**Issue by jedorey** [dereneaton/ipyrad#330]
ipyrad v. 0.7.30
ToyPlot v. 0.18.0
ToyTree v. 0.1.21

```
>>> bb.generate_tests_from_tree(
constraint_dict={
"p4": ["sample1", "sample2"],
"p3": ["sample3", "sample"],
})
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/rsleith/miniconda2/lib/python2.7/site-packages/ipyrad/analysis/baba.py", line 194, in generate_tests_from_tree
    tests = tree2tests(self.newick, constraint_dict, constraint_exact)
  File "/home/rsleith/miniconda2/lib/python2.7/site-packages/ipyrad/analysis/baba.py", line 674, in tree2tests
    for topnode in tree.tree.traverse("levelorder"):
AttributeError: ToyTree instance has no attribute 'tree'
```

The issue seems to be the command `for topnode in tree.tree.traverse("levelorder")` in line 674 of baba.py. I wonder if it should be `for topnode in tree.treenode.traverse("levelorder")`.

**Comment by isaacovercast** [comment]
Yep, it sure should be that. I fixed it in commit 933df345..05bf8a45. Didn't push the conda package, but you can pull it from github for now. Thanks for reporting.
