### ISSUE TITLE
tmx.draw_tree() error

### ISSUE THREAD

**Issue by siyeongjun** [dereneaton/ipyrad#516]
I follwed the treemix commands, and it worked well. 
However, I found an error in the last part of the treemix code

>>> imap = {
    "Matsu": ["Matsu_1", "Matsu_2", "Matsu_3", "Matsu_4", "Matsu_5", "Matsu_6"],
    "Nemuro": ["Nemuro_1", "Nemuro_2", "Nemuro_3", "Nemuro_4", "Nemuro_5", "Nemuro_6"],
    "USA": ["USA1", "USA2", "USA3", "USA4", "USA5", "USA6"],
    "WGS": ["WGS_1", "WGS_2", "WGS_3", "WGS_4", "WGS_5", "WGS_6"],
    }
>>> minmap = {i: 0.7 for i in imap}

>>> tmx = ipa.treemix(
       data=data,
...     imap=imap,
...     minmap=minmap,
...     seed=123456,
...     root="Nemuro,WGS",
...     m=2,
... )
Samples: 24
Sites before filtering: 139154
Filtered (indels): 0
Filtered (bi-allel): 0
Filtered (mincov): 0
Filtered (minmap): 28075
Filtered (combined): 28075
Sites after filtering: 111079
Sites containing missing values: 109484 (98.56%)
Missing values in SNP matrix: 197669 (7.41%)
subsampled 20325 unlinked SNPs
>>> tmx.run()
>>> tmx.draw_tree();
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.7/site-packages/ipyrad/analysis/treemix.py", line 284, in draw_tree
    scalebar=True,
ValueError: too many values to unpack (expected 2)

**Comment by siyeongjun** [comment]
Thank your reply.
But still the same error exist.

>>> tmx.draw_tree();
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.7/site-packages/ipyrad/analysis/treemix.py", line 284, in draw_tree
    scalebar=True,
ValueError: too many values to unpack (expected 2)

**Comment by isaacovercast** [comment]
Can you also check your version of ipyrad? It also may be out of date. The current version is 0.9.92.

`conda update -c conda-forge -c bioconda ipyrad=0.9.92`
