### ISSUE TITLE
An Error in Step3  # splitting loci so first file is smaller and last file is bigger

### ISSUE THREAD

**Issue by jljy47** [dereneaton/ipyrad#530]
Hi,
we met an Error in Step3 showing that

> Message: KeyboardInterrupt: 
-> 1255         inclusts = iter(clustio.read().strip().split("//\n//\n"))
 > # splitting loci so first file is smaller and last file is bigger

1) What is the reason?  Can we continue with it or have to restart it from Step3?
2) Is the Error caused by running with another ipyrad process in Step7 at the same time?(  Message: KeyboardInterrupt: )   I did this once before but didn't have this problem.   

`data.run("123456")
Parallel connection | nku-PowerEdge-T640: 60 cores
[####################] 100% 0:05:36 | loading reads        | s1 |
[####################] 100% 0:50:53 | processing reads     | s2 |
[####################] 100% 0:43:29 | join merged pairs    | s3 |
[####################] 100% 1:12:11 | join unmerged pairs  | s3 |
[####################] 100% 0:40:03 | dereplicating        | s3 |
[####################] 100% 5 days, 3:47:53 | clustering/mapping   | s3 ||
[####################] 100% 0:01:11 | building clusters    | s3 |
[####################] 100% 0:00:12 | chunking clusters    | s3 |

Encountered an Error.
Message: KeyboardInterrupt: 
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<string> in <module>

~/miniconda3/envs/ipyrad/lib/python3.9/site-packages/ipyrad/assemble/clustmap.py in muscle_chunker(data, sample)
   1253         # write optim clusters to each tmp file
   1254         clustio = open(clustfile, 'rt')
-> 1255         inclusts = iter(clustio.read().strip().split("//\n//\n"))
   1256 
   1257         # splitting loci so first file is smaller and last file is bigger

KeyboardInterrupt: 

data.run("4")

Parallel connection | nku-PowerEdge-T640: 60 cores
skipping samples not in state==3:
['OUT1', 'OUT2', 'OUT3', 'cr-CQJFS1', 'cr-CQJFS2', 'cr-CQJFS3', 'cr-CQSZ1', 'cr-CQSZ2', 'cr-CQSZ3', 'cr-CQSZ4', 'cr-FJLY1', 'cr-GDCBL1', 'cr-GDNL1', 'cr-GDNL2', 'cr-GXCZ1', 'cr-GXCZ2', 'cr-GXGL1', 'cr-GXGL2', 'cr-GXHC1', 'cr-GXJX1', 'cr-GXJX2', 'cr-GZBJ1', 'cr-GZBJ2', 'cr-GZKKS1', 'cr-GZKKS2', 'cr-GZLD1', 'cr-GZLGS1', 'cr-GZLGS2', 'cr-GZLGS3', 'cr-GZLGS4', 'cr-GZLGS5', 'cr-HNNS1', 'cr-JXJGS1', 'cr-JXJGS2', 'cr-JXJGS3', 'cr-JXJGS4', 'cr-JXJLS1', 'cr-LAOS1', 'cr-SCDB1', 'cr-SCDB2', 'cr-SCDB3', 'cr-SCDB4', 'cr-SCDB5', 'cr-SCDB6', 'cr-SCDJY1', 'cr-SCDJY2', 'cr-SCDJY3', 'cr-SCDJY4', 'cr-SCDJY5', 'cr-SCLD1', 'cr-SCLD2', 'cr-SCLD3', 'cr-SCLD4', 'cr-SCLD5', 'cr-SCLD6', 'cr-SCLS1', 'cr-SCLS2', 'cr-SCLS3', 'cr-SCMY1', 'cr-SCMY2', 'cr-SCNC1', 'cr-SCNC2', 'cr-SCNC3', 'cr-SCQC1', 'cr-SCQC2', 'cr-SCWC1', 'cr-SNJE1', 'cr-SNJE2', 'cr-SNJY3', 'cr-SNJY5', 'cr-SXQL3', 'cr-SXQL4', 'cr-SXSY1', 'cr-SXSY2', 'cr-SXSY3', 'cr-SXSY4', 'cr-SXSY5', 'cr-SXYX1', 'cr-TWALS1', 'cr-TWALS2', 'cr-TWALS3', 'cr-TWGX1', 'cr-TWGX2', 'cr-TWGX3', 'cr-TWNT1', 'cr-TWNT2', 'cr-TWNTLS1', 'cr-TWNTLS2', 'cr-TWPD1', 'cr-TWTD1', 'cr-TWTS1', 'cr-TWTS2', 'cr-TWTS3', 'cr-TWXB1', 'cr-TWXB2', 'cr-TWYL1', 'cr-TWYL2', 'cr-XZBJL1', 'cr-XZBJL2', 'cr-XZBJL3', 'cr-XZBM1', 'cr-XZBM2', 'cr-XZBM3', 'cr-XZCY1', 'cr-XZCY2', 'cr-XZCY3', 'cr-XZCY4', 'cr-XZCY5', 'cr-XZJL1', 'cr-XZJL2', 'cr-XZJL3', 'cr-XZJL4', 'cr-XZSN1', 'cr-XZSN2', 'cr-YNDL1', 'cr-YNDL2', 'cr-YNDL3', 'cr-YNDL4', 'cr-YNDL5', 'cr-YNDQ1', 'cr-YNDQ2', 'cr-YNGN1', 'cr-YNGN2', 'cr-YNGN3', 'cr-YNGN4', 'cr-YNGN5', 'cr-YNHZ1', 'cr-YNHZ2', 'cr-YNHZ3', 'cr-YNHZ4', 'cr-YNHZ5', 'cr-YNHZ6', 'cr-YNJH1', 'cr-YNJH2', 'cr-YNJH3', 'cr-YNJH4', 'cr-YNJH5', 'cr-YNJP1', 'cr-YNJP2', 'cr-YNJP3', 'cr-YNKM2', 'cr-YNKM3', 'cr-YNKM4', 'cr-YNKM5', 'cr-YNLC1', 'cr-YNLC4', 'cr-YNLC5', 'cr-YNLS1', 'cr-YNLS2', 'cr-YNLS3', 'cr-YNLS4', 'cr-YNPB1', 'cr-YNPB2', 'cr-YNPB3', 'cr-YNRL1', 'cr-YNRL2', 'cr-YNRL3', 'cr-YNRL4', 'cr-YNSZ1', 'cr-YNSZ2', 'cr-YNSZ3', 'cr-YNSZ4', 'cr-YNSZ5', 'cr-YNYJ1', 'cr-YNYJ2', 'cr-YNYJ3', 'cr-YNYL1', 'cr-YNYL2', 'cr-YNYL3', 'cr-YNYL4', 'cr-YNYL5', 'cr-YNZT1', 'cr-ZJQY1', 'cr-ZJQY2', 'cr-ZJWYL1', 'cr_CRDPS1', 'cr_CRTC1', 'cr_CSXZY1', 'in-XZRKZ1', 'in-XZRKZ2', 'in-XZRKZ3', 'in-XZRKZ4', 'in-XZRKZ5']

Encountered an Error.
Message: no samples ready for step 4
Traceback (most recent call last):
  File "/home/nku/miniconda3/envs/ipyrad/lib/python3.9/site-packages/ipyrad/core/Parallel.py", line 314, in wrap_run
    self.tool._run(ipyclient=self.ipyclient, **self.rkwargs)
  File "/home/nku/miniconda3/envs/ipyrad/lib/python3.9/site-packages/ipyrad/core/assembly.py", line 696, in _run
    stepdict[step](self, force, ipyclient).run()
  File "/home/nku/miniconda3/envs/ipyrad/lib/python3.9/site-packages/ipyrad/assemble/jointestimate.py", line 38, in __init__
    self.samples = self.get_subsamples()
  File "/home/nku/miniconda3/envs/ipyrad/lib/python3.9/site-packages/ipyrad/assemble/jointestimate.py", line 89, in get_subsamples
    raise IPyradError("no samples ready for step 4")
ipyrad.assemble.utils.IPyradError: no samples ready for step 4
`

Thank you so much~

**Comment by isaacovercast** [comment]
The KeyboardInterrupt error indicates that you either pushed ctrl+c or you pushed the stop button on the jupyter notebook. If you killed during step 3 then you will need to run step 3 over again. The reason it says 'no samples ready for step 4' when you try to run step 4 is because none of the samples finished running step 3. Please run step 3 again.

**Comment by jljy47** [comment]
So the error has nothing to do with this situation right？

1257 # splitting loci so first file is smaller and last file is bigger

**Comment by isaacovercast** [comment]
No, the error was not that, it was KeyboardInterrupt, which means the process was force quit. The line you indicate is a comment in the code on line 1257 to indicate what that code is doing and just happens to be where the code was executing when it was killed.

**Comment by jljy47** [comment]
Thank you so much for your help every time, Isaac~

**Comment by isaacovercast** [comment]
No prob!
