### ISSUE TITLE
Refseq mapping - Better handling for missing bam_to_fastq tmpfiles

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#92]
Running step3 hybrid on glenn's gbs data 99% of everything was fine for all samples, but one sample errored out here:
```
Exception: one or more exceptions from call to method: get_aligned_reads
[6:apply]: OSError: [Errno 2] No such file or directory: '/Users/glenn/ipyrad/.isaac_test/work/work_refmapping/cra-ant-72907-Ancash-Pacar-mapped.bamscaffold25662974R1.fq'
[12:apply]: OSError: [Errno 2] No such file or directory: '/Users/glenn/ipyrad/.isaac_test/work/work_refmapping/cra-ant-72907-Ancash-Pacar-mapped.bamscaffold578115851R1.fq'
Traceback (most recent call last):
  File "/usr/local/opt/anaconda/bin/ipyrad", line 9, in <module>
    load_entry_point('ipyrad==0.1.32', 'console_scripts', 'ipyrad')()
  File "/usr/local/opt/anaconda/lib/python2.7/site-packages/ipyrad-0.1.32-py2.7.egg/ipyrad/__main__.py", line 279, in main
    data.run(steps=steps, force=args.force, preview=args.preview)
  File "/usr/local/opt/anaconda/lib/python2.7/site-packages/ipyrad-0.1.32-py2.7.egg/ipyrad/core/assembly.py", line 1239, in run
    self.step3(force=force, preview=preview)
  File "/usr/local/opt/anaconda/lib/python2.7/site-packages/ipyrad-0.1.32-py2.7.egg/ipyrad/core/assembly.py", line 1135, in step3
    [samples, noreverse, force, preview], 10)
  File "/usr/local/opt/anaconda/lib/python2.7/site-packages/ipyrad-0.1.32-py2.7.egg/ipyrad/core/assembly.py", line 779, in _clientwrapper
    raise inst
ipyparallel.error.CompositeError: one or more exceptions from call to method: get_aligned_reads
[6:apply]: OSError: [Errno 2] No such file or directory: '/Users/glenn/ipyrad/.isaac_test/work/work_refmapping/cra-ant-72907-Ancash-Pacar-mapped.bamscaffold25662974R1.fq'
[12:apply]: OSError: [Errno 2] No such file or directory: '/Users/glenn/ipyrad/.isaac_test/work/work_refmapping/cra-ant-72907-Ancash-Pacar-mapped.bamscaffold578115851R1.fq'

```

First of all, it didn't clean up the other tmpfiles on the way out. Second of all, where'd this fuckin file go? Third of all, seems like you could just catch this error and pass. Its literally 1 in a million reads. I'd like to figure it out at least.

**Comment by isaacovercast** [comment]
This might happen if two ipclients got ahold of the same sample.... hm.

**Comment by isaacovercast** [comment]
This is a red herring. It's erroring out on the last sample. Maybe it's trying to double clean up the tmp files for this sample? In a full run it gets all the way to the end, clust.gz files are updated for the last sample called, but then it bombs trying to do cleanup, i think.

**Comment by isaacovercast** [comment]
Fixed. Better handling of cleaning up tmp files.
